✨️ Add feature to remove SSL from site command
EasyEngine/site-command pull request #386
Opened 2021-07-08 09:50 UTC by kirtangajjar

2021-07-09 03:04 UTC, mrrobot47 requested changes
Have you checked the scenario where you re-enable SSL after switching it off?
Is it using the existing certificate or requesting a new one?
If it is using the existing one, is it checking for expiry or not?

2021-07-09 03:04 UTC, mrrobot47 commented on src/helper/class-ee-site.php
> +		$this->dump_docker_compose_yml([ 'nohttps' => 'nohttps' ]);
Please keep the `nohttps` value boolean like in the rest of the file.

2021-07-09 07:39 UTC, kirtangajjar commented on src/helper/class-ee-site.php
> +	 *   - "off"
This is required, as unquoted "off" is interpreted as false(boolean) by our YAML parser.

2021-07-09 07:41 UTC, kirtangajjar commented on src/helper/class-ee-site.php
> +	 *   - "off"
Yes, I have checked the scenario of re-enabling SSL after switching it off. It uses the existing certificate, and also checks for expiry.

2021-08-23 14:51 UTC, mrrobot47 approved these changes

2021-08-23 14:51 UTC, merged